### ISSUE TITLE
Check target feature type

### ISSUE THREAD

**Issue by macetheace96** [byu-dml/metalearn#48]
Since we currently don't handle regression tasks, we should check the target feature type and throw an error if it is not categorical

**Comment by MichaelMMeskhi** [comment]
Just implement a level of measure on the target to check its type. Return a error if it falls into regression. i.e. check if target nominal, ratio, interval, etc...

**Comment by macetheace96** [comment]
is it possible to have a regression problem that would use an int data type instead of a float?

**Comment by macetheace96** [comment]
or for a classification problem to use float?

**Comment by bjschoenfeld** [comment]
Integer regression sounds like integer programming, which is NP-complete, but is a possible problem. If the user specifies whether the target is numeric vs categorical, then it does not matter the datatype - we use that to determine regression vs classification. On the other hand, if we are inferring column types, any numeric python type will be treated as a NUMERIC column type and therefore regression; otherwise CATEGORICAL and classification.
